LaserDynamics/Application/urls.py
from django.urls import path


from . import views

app_name = 'Application'
urlpatterns = [
    path('', views.index, name='index'),
    path('redirectTest/', views.redirectTest, name='redirectTest'),
    path('userLogin/', views.userLogin, name="userLogin"),
    path('signup/', views.signup, name='signup'),
    path('account/',views.account, name='account'),
    path('account/logoutPage/', views.logoutPage, name = "logoutPage"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
]

LaserDynamics/LaserDynamics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('Application/images/lasers.jpg'))),

    path('admin/', admin.site.urls),
    path('application/', include('Application.urls')),
]

LaserDynamics/Application/models.py
from django.db import models

# Create your models here.
from django.dispatch import receiver


from django.db.models.signals import post_save


from django.contrib.auth.models import User






class CustomUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)


    def __str__(self):
        return "User -> " + self.user.username
    

#this method is to create CustomUser when User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        CustomUser.objects.create(user=instance)

#this method to update profile when user is updated
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.customuser.save()




class Items(models.Model):
    price = models.FloatField(default = 0)

LaserDynamics/Application/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required






# Create your views here.
def index(request):
    # send_mail(subject = 'Thank you for signing up!', 
    #           message = 'Someone visited the index page!',
    #           from_email = settings.EMAIL_HOST_USER,
    #           recipient_list=['mhanks445@yahoo.com'],
    #           fail_silently=False,

    #           )

    return render(request, 'Application/index.html')



def logoutPage(request):
    logout(request)
    return redirect(reverse('Application:userLogin'))




def userLogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect(reverse('Application:account'))
        
        else:
            context = {'errorMessage': "Invalid login credentials, please try again!"}
            return render(request, 'Application/login.html', context)
    return render(request,'Application/login.html')


def signup(request):
    if request.method == 'POST':
        user = User.objects.create_user(username = request.POST['username'],
                                        password = request.POST['password'], 
                                        email = request.POST['email'], 
                                        first_name = request.POST['firstName'], 
                                        last_name = request.POST['lastName'])
        user.save()
        return render(request, 'Application/login.html', {})
    return render(request,'Application/signup.html', {})

@login_required(login_url='Application:userLogin')
def account(request):
    return render(request, "Application/account.html")



def redirectTest(request):
    return redirect(reverse('Application:index'))




def aboutUs(request):
    return render(request,'Application/aboutUs.html')

LaserDynamics/Application/templates/Application/aboutUs.html
<!DOCTYPE html>
<html>
    <body>
        <h1>
            This is the about us page!
        </h1>
    </body>
</html>

LaserDynamics/Application/templates/Application/account.html
<!DOCTYPE html>
<html>
    <body>
        <h1>
            You successfully logged in!
        </h1>
        <a href = "{% url 'Application:logoutPage' %}">Logout</a>
    </body>
</html>

LaserDynamics/Application/templates/Application/index.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <link rel = "stylesheet" href= "{% static 'Application/style.css' %}" >
    </head>
    <body>
        <div>
        <div class = 'testing'>
        <h1 >Laser Dynamics</h1>
        <a href = "{% url 'Application:userLogin' %}">Login Page</a>
        <a href = "{% url 'Application:aboutUs' %}">About us Page</a>
        </div>
    </div>
    </body>
</html>

LaserDynamics/Application/templates/Application/login.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <link rel = "stylesheet" href= "{% static 'Application/style.css' %}" >
    </head>
    <body>
        
    


        <div>
        <div class = 'testing'>
            <h1 >Laser Dynamics</h1>
        
        <form action="{% url 'Application:userLogin' %}" method="post">
            {% csrf_token %}
                <div>
                    <label for="username"><b>Username</b></label>
                    <input type="text" placeholder="Enter Username" name="username" required>
                    <label for="password"><b>Password</b></label>
                    <input type="password" placeholder="Enter Password" name="password" required>
                    <button type="submit">Login</button>
                    <a href="{% url 'Application:signup' %}">Not a user?</a>
                </div>
            </form>

        </div>
    </div>
    </body>
</html>

LaserDynamics/Application/templates/Application/signup.html
<!DOCTYPE html>
<html>
    <body>
        <div >
            <form action="{% url 'Application:signup' %}" method="post">
            {% csrf_token %}
            <input type="text"  name="firstName" id="firstName" aria-describedby="First Name" placeholder="Enter your first name">
            <input type="text"  name="lastName" id="lastName" aria-describedby="Last Name" placeholder="Enter your last Name">
            <input type="text" name="username" id="username" aria-describedby="User Name" placeholder="Enter Username">
            <input type="email" name="email" id="email" aria-describedby="E-mail" placeholder="Enter a valid email address">
            <input type="password"  name="password" id="password" placeholder="Enter a Password">
        
          <button type="submit" >Create Account</button>
                    <a href="{% url 'Application:userLogin' %}">Already a user?</a>
        
        </form>
        
        </div>
    </body>
</html>